### ISSUE TITLE
Rückmeldung Zeitformat (jetzt in GMT)

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.simple-api#1]
Vielleicht ist es ja auch so üblich...

Der Adapter meldet als Rückgabe die GMT Zeit:

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Type: text/plain
Date: Sat, 25 Jun 2016 10:59:42 GMT
Connection: keep-alive
Content-Length: 99

Die Systemzeit betrug zu dem Zeitpunkt 12:59:42.

Ich würde mir wünschen, dass man beim Adapter einstellen kann, dass die Systemzeit ausgegeben wird, so wie sie eingestellt ist. In den ioBroker Objekten wird als Zeitstempel 12:59:42 eingetragen und nciht die GMT Zeit.

**Comment by Apollon77** [comment]
closed because inactivity
