### ISSUE TITLE
get: "ts" is not state.ts

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.simple-api#100]
[Siehe Forum](https://forum.iobroker.net/post/718119).

get liefert in "ts" anstelle von state.ts den Zeitpunkt vom Erstellen des Datenpunktes. "from" stimmt ebenfalls nicht.

Web-Adapter 3.4.16
Simple-API-Adapter 2.6.2

**Comment by neo4a** [comment]
Wrong values for object prperties .lc und .ts for objects located in 0_userdata.0

For objects in adapter nodes values for .ls and .lc are correct.

Simple-API-Adapter 2.6.1

**Comment by Apollon77** [comment]
Sorry, but I do not get it ... 

* .ts exit in objects (and mean "last timestamp object update) and objects do not have an .lc
* .ts and .lc on the "state" level mean timestamp and lastchange for that state value

**Comment by neo4a** [comment]
In myy first attempt I was only calling   setState(dpAndreas, ! getState(dpAndreas).val) without ack-parameter.
Then .lc-value in simple api request was never refreshed.

I updated my script by involving ack parameter and now it is working. (Background: I use a smart button and Alexa command to set status flags for updating several pc and tablet pc accordingly.)
Thanks.


`const cSWAndreas = ["mihome.0.devices.switch_158d00018b46ff.click"]; 

const cDP = "0_userdata.0.Fitness.";

const dpAndreas = cDP + "Andreas.Click";
  DoCreateObj(dpAndreas, {read: true, write: true, name: 'Andreas hat Taster gedrückt', desc: '',  type: "boolean"});

on({id: cSWAndreas, val: true}, function (obj) {
  setState(dpAndreas, ! getState(dpAndreas).val, true);
  console.log('Andreas Click');
});`

http://192.168.178.26:8087/get/0_userdata.0.Fitness.Andreas.Click

{"val":true,"ack":true,"ts":1643206250223,"q":0,"c":"script.js.Andreas.Fitness.FitnessClock","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1643206912616,"type":"state","common":{"read":true,"write":true,"name":"Andreas hat Taster gedrückt","desc":"","type":"boolean"},"_id":"0_userdata.0.Fitness.Andreas.Click","acl":{"object":1636,"state":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}

**Comment by Apollon77** [comment]
In fact "lc" is only checked if the value is changed, so assumption is that you do not really changed the value.

**Comment by neo4a** [comment]
> In fact "lc" is only checked if the value is changed

That behavior differs from admin object tree where lc values is always updated even state value is not changed but touched. 

Simple Api is following its own logic at this point :)

**Comment by Apollon77** [comment]
@paul53 Ja deswegen ist der noch offen ... die "lc" diskussion ist ja eigentlich Themenfremd in dem issue :-) aber danke fürs pinpointen

**Comment by Apollon77** [comment]
Please try GitHub version
