### ISSUE TITLE
Wish: Adapter settings - single IP adresses

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.simple-api#11]
Many thanks for this adapter, I am successfully using it ([ioBroker forum thread](https://forum.iobroker.net/viewtopic.php?f=35&t=19004&p=198483#p198483)).

For security purposes, I vote for an option to enter certain IP addresses or ranges in the adapter configuration. The adapter currently just provides a drop down field, but it is not possible to enter certain IPs which should then be the only ones to communicate with the adapter.

Thanks.

**Comment by Apollon77** [comment]
IPs csn be faked very easiely ... so this do not really bring more security.

The best practice would be to create users for API access, assign correct rights to the affected datapoints to access and then use authentication (username/password) for the access. Please try that

**Comment by Mic-M** [comment]
Wow, thanks for your swift response and feedback. I wasn't really aware of what you are stating, but makes very much sense. Not much of a concern for me anyway since I am using it in a local, private network only, but was something I have noticed when setting up the adapter. 
So based on your response and provided resolution: please consider as resolved. Thanks.
