### ISSUE TITLE
Hashs in URL

### ISSUE THREAD

**Issue by chris25197** [ioBroker/ioBroker.simple-api#12]
Hallo,

ich habe den simple-api 2.0.0 unter ioBroker 3.5.10 laufen. Allerdings können keine Hashs (#) in der URL genutzt werden. In der Kodierten Form (%23) habe ich es ebenfalls probiert. 
Können Sie mir hier weiterhelfen? 

Getätigt mit Firefox 64.0

Gruß, Chris

**Comment by Apollon77** [comment]
Siehe Forum.Bitte Debug Log senden

**Comment by chris25197** [comment]
Hallo Apollon77,

hier der Debug LOG:
![grafik](https://user-images.githubusercontent.com/45920671/50087416-4a38c200-0200-11e9-9b9e-5234b485c893.png)

hier der zweite Aufruf:
![grafik](https://user-images.githubusercontent.com/45920671/50087499-8b30d680-0200-11e9-9ee3-bac5e1903fc3.png)

hier der erste Aufruf:
![grafik](https://user-images.githubusercontent.com/45920671/50087538-aac7ff00-0200-11e9-84b0-bd8476b306e7.png)

Hier der Objekt:
![grafik](https://user-images.githubusercontent.com/45920671/50087592-d945da00-0200-11e9-941d-bdbfb28ab2e3.png)

Im Forum habe ich leider nix gefunden. Wäre dankbar wenn Du mir hier weiterhelfen würdest, damit ich fundiertere Meldungen erstellen kann. Vielen Dank.

Gruß, Chris

**Comment by Apollon77** [comment]
Es sollte mit den Logs an siuch durch manuelles decoding von %23 getan sein. Schaue rein

**Comment by Apollon77** [comment]
Bitte GitHub 2.0.1 versuchen!

**Comment by chris25197** [comment]
mit der 2.0.2 getestet, funktioniert. Vielen Dank.
