### ISSUE TITLE
SetBulk saves to javascript.0 after upgrade to javascript 

### ISSUE THREAD

**Issue by stuckmcx** [ioBroker/ioBroker.simple-api#123]
**Describe the bug**  
Since yesterday, when upgrade the js-controller to 4.0.15 my Script with send my PV Data to iobroker via SimpleAPI saves its parameters to javascript.0

**Web request**
`http://192.168.178.4:8087/setBulk?0_userdata.0.PV.DateTime=2022-02-27-15:38&0_userdata.0.PV.id=PVL2300N20819025&0_userdata.0.PV.temp=33.4&0_userdata.0.PV.v_pv1=231.9&v_pv2=0.0&v_pv3=0.0&i_pv1=6.7&i_pv2=0.0&i_pv3=0.0&i_ac1=6.2&i_ac2=0.0&i_ac3=0.0&0_userdata.0.PV.v_ac1=239.2&v_ac2=0.0&v_ac3=0.0&f_ac1=50.01&0_userdata.0.PV.p_ac1=1506&f_ac2=0.0&p_ac2=0&f_ac3=0.0&p_ac3=0&e_today=8.75&e_total=262.35&h_total=859&prettyPrint`

**Web output**
`[ { "id": "0_userdata.0.PV.DateTime", "val": "2022-02-27-15:38", "value": "2022-02-27-15:38" }, { "id": "0_userdata.0.PV.id", "val": "PVL2300N20819025", "value": "PVL2300N20819025" }, { "id": "0_userdata.0.PV.temp", "val": 33.4, "value": 33.4 }, { "id": "0_userdata.0.PV.v_pv1", "val": 231.9, "value": 231.9 }, { "id": "0_userdata.0.PV.v_ac1", "val": 239.2, "value": 239.2 }, { "id": "0_userdata.0.PV.p_ac1", "val": 1506, "value": 1506 }, { "id": "0_userdata.0.PV.v_pv2", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.v_pv3", "val": "0.0", "value": "0.0" }, { "id": "javascript.0.i_pv1", "val": 6.7, "value": 6.7 }, { "id": "0_userdata.0.PV.i_pv2", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.i_pv3", "val": "0.0", "value": "0.0" }, { "id": "javascript.0.i_ac1", "val": 6.2, "value": 6.2 }, { "id": "0_userdata.0.PV.i_ac2", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.i_ac3", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.v_ac2", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.v_ac3", "val": "0.0", "value": "0.0" }, { "id": "javascript.0.f_ac1", "val": 50.01, "value": 50.01 }, { "id": "0_userdata.0.PV.f_ac2", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.p_ac2", "val": 0, "value": 0 }, { "id": "0_userdata.0.PV.f_ac3", "val": "0.0", "value": "0.0" }, { "id": "0_userdata.0.PV.p_ac3", "val": 0, "value": 0 }, { "id": "javascript.0.e_today", "val": 8.75, "value": 8.75 }, { "id": "javascript.0.e_total", "val": 262.35, "value": 262.35 }, { "id": "0_userdata.0.PV.h_total", "val": 859, "value": 859 } ]`

**Notes**  
i tried to add the 0_userdata.0.PV.  to the web request, but this doesnt make any difference.

**Expected behavior**  
Data will updated the correct value

**Versions:**  
 - Adapter version: 2.6.3 (2.6.2 same behavior)
 - JS-Controller version: 4.0.15
 - Node version: v14.19.0
 - Operating system: Ubuntu 20.04.4 LTS

Hope this are enough informations.

Greetz
Marc

**Comment by Apollon77** [comment]
Ok, you need to provide some more background please. How is your states looking like? It seems to me that you update values by providing names and state-IDs in a mixed way ... So please simplyify that example to ideally ONE state where it happens and then provide more dwtails. is maybe the same "name" existing twice in your system?
