### ISSUE TITLE
query history adapter

### ISSUE THREAD

**Issue by froggi1930** [ioBroker/ioBroker.simple-api#135]
The query will only return the latest datapoint regardless of which time (from - to) is set.

**Comment by Apollon77** [comment]
Please provide details how your call looks like

**Comment by froggi1930** [comment]
The call is like this...
`http://192.168.178.222:8087/query/javascript.0.ShellyVerbrauch.SHPLG-S%231D3709%231.Relay0.gestern?dateFrom=2022-04-01T12:00:00.000Z&dateTo=2022-04-08T01:00:10.000Z`

As a result I only get the latest datapoint...

`[
--
  | {
  | "target": "javascript.0.ShellyVerbrauch.SHPLG-S#1D3709#1.Relay0.gestern",
  | "datapoints": [
  | [
  | 409.55,
  | 1649541600417
  | ]
  | ]
  | }
  | ]
`

**Comment by Apollon77** [comment]
Ok, lets iterate in Forum
