### ISSUE TITLE
GetPlainValue not working as expected.

### ISSUE THREAD

**Issue by lumo2707** [ioBroker/ioBroker.simple-api#148]
**Describe the bug**  
When i am trying to get a value from an ioBroker object i got the following error:
**error: datapoint "weatherunderground.0.forecast.current.temp" not found**

My call is:
http://192.168.178.138:8087/getPlainValue/weatherunderground.0.forecast.current.temp

The object is generated by WeatherUnderground and has the following structure:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/8993387/172182378-7be97e10-702c-4a3f-b2c9-4d5f49740b05.png">

Other calls like getting the windDirection with http://192.168.178.138:8087/getPlainValue/weatherunderground.0.forecast.current.windDirection is working, but not for temp and wind.

**Expected behavior**  
Get the temperature value

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.7.0
 - JS-Controller version: 4.0.23
 - Node version: v16.15.1
 - Operating system: Linux, Raspberry

**Comment by lumo2707** [comment]
Sorry, my fault:

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/8993387/172207458-0be68140-a722-45f9-a3f4-69755c10011b.png">

**Comment by Apollon77** [comment]
Very interesting.

Please execute in a shell

`iob state get weatherunderground.0.forecast.current.temp`
