### ISSUE TITLE
Arrays stored in data points are not displayed correctly.

### ISSUE THREAD

**Issue by kugelkopf123** [ioBroker/ioBroker.simple-api#15]
I save an array to pass it to another system. Unfortunately, the array is not displayed correctly. The problem is the quotes in front and end of the square brackets.
So it is not a properly stored JSON array and there are problems parsing it:
 "javascript.0.Wetterstation.HistTemp1": {
    "val": "[-1.24,-0.67,-.....
As far as i see there is no problem as log it is a single value.
Is there a quick fix?
SimpleApi output:

```
{
  "javascript.0.Wetterstation.TempDraussenMin": {
    "val": -0.1,
    "ack": false,
    "ts": 1549216440089,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549216440080
  },
  "javascript.0.Wetterstation.TempDraussenMax": {
    "val": 5.5,
    "ack": false,
    "ts": 1549198440031,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549198440031
  },
  "javascript.0.Wetterstation.TempDraussenMinTime": {
    "val": "18:54:00 - 03.02.2019",
    "ack": false,
    "ts": 1549216440096,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549216440096
  },
  "javascript.0.Wetterstation.TempDraussenMaxTime": {
    "val": "13:54:00 - 03.02.2019",
    "ack": false,
    "ts": 1549198440034,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549198440034
  },
  "javascript.0.Wetterstation.LastResetMinMax": {
    "val": "11:45:40 - 03.02.2019",
    "ack": false,
    "ts": 1549190740415,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549190740415
  },
  "javascript.0.Wetterstation.UpdateAnAus": {
    "val": false,
    "ack": false,
    "ts": 1548212875725,
    "q": 0,
    "from": "system.adapter.admin.0",
    "lc": 1548212875725
  },
  "javascript.0.Wetterstation.ResetMinMax": {
    "val": true,
    "ack": false,
    "ts": 1549190740396,
    "q": 0,
    "from": "system.adapter.web.0",
    "lc": 1547985029727
  },
  "javascript.0.Wetterstation.HistTemp1Date": {
    "val": "[\"2019-1-31 20:00:00\",\"2019-1-31 21:00:00\",\"2019-1-31 22:00:00\",\"2019-1-31 23:00:00\",\"2019-2-1 00:00:00\",\"2019-2-1 01:00:00\",\"2019-2-1 02:00:00\",\"2019-2-1 03:00:00\",\"2019-2-1 04:00:00\",\"2019-2-1 05:00:00\",\"2019-2-1 06:00:00\",\"2019-2-1 07:00:00\",\"2019-2-1 08:00:00\",\"2019-2-1 09:00:00\",\"2019-2-1 10:00:00\",\"2019-2-1 11:00:00\",\"2019-2-1 12:00:00\",\"2019-2-1 13:00:00\",\"2019-2-1 14:00:00\",\"2019-2-1 15:00:00\",\"2019-2-1 16:00:00\",\"2019-2-1 17:00:00\",\"2019-2-1 18:00:00\",\"2019-2-1 20:00:00\",\"2019-2-1 21:00:00\",\"2019-2-1 22:00:00\",\"2019-2-1 23:00:00\",\"2019-2-2 00:00:00\",\"2019-2-2 01:00:00\",\"2019-2-2 02:00:00\",\"2019-2-2 03:00:00\",\"2019-2-2 04:00:00\",\"2019-2-2 05:00:00\",\"2019-2-2 06:00:00\",\"2019-2-2 07:00:00\",\"2019-2-2 08:00:00\",\"2019-2-2 09:00:00\",\"2019-2-2 10:00:00\",\"2019-2-2 11:00:00\",\"2019-2-2 12:00:00\",\"2019-2-2 13:00:00\",\"2019-2-2 14:00:00\",\"2019-2-2 15:00:00\",\"2019-2-2 16:00:00\",\"2019-2-2 17:00:00\",\"2019-2-2 18:00:00\",\"2019-2-2 19:00:00\",\"2019-2-2 20:00:00\",\"2019-2-2 21:00:00\",\"2019-2-2 22:00:00\",\"2019-2-2 23:00:00\",\"2019-2-3 00:00:00\",\"2019-2-3 01:00:00\",\"2019-2-3 02:00:00\",\"2019-2-3 03:00:00\",\"2019-2-3 04:00:00\",\"2019-2-3 05:00:00\",\"2019-2-3 06:00:00\",\"2019-2-3 07:00:00\",\"2019-2-3 08:00:00\",\"2019-2-3 09:00:00\",\"2019-2-3 10:00:00\",\"2019-2-3 11:00:00\",\"2019-2-3 12:00:00\",\"2019-2-3 13:00:00\",\"2019-2-3 14:00:00\",\"2019-2-3 15:00:00\",\"2019-2-3 16:00:00\",\"2019-2-3 17:00:00\",\"2019-2-3 18:00:00\"]",
    "ack": false,
    "ts": 1549217316165,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549217316165
  },
  "javascript.0.Wetterstation.HistTemp1": {
    "val": "[-1.24,-0.67,-0.13,-0.58,-1.26,-1.81,-1.49,-0.75,-0.52,-0.4,-0.04,0,-0.13,-0.06,0.37,0.87,1.51,1.78,3.05,3.7,3.7,3.06,2.48,2.09,1.9,0.93,-0.28,-0.64,-0.49,-0.36,-0.31,-0.06,0.15,0.42,0.65,0.58,0.39,0.62,1.09,1.31,0.83,0.71,1.04,0.94,0.5,0.59,0.54,0.5,0.56,0.4,-0.34,-0.13,0.11,0.2,-0.02,-0.37,0.03,-0.21,-0.53,-1.05,-0.86,-0.49,0.36,1.77,3.86,4.96,5.13,5.21,4.14,1.48]",
    "ack": false,
    "ts": 1549217316168,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549217288962
  }
}
```

**Comment by Apollon77** [comment]
What exactly is the problem? val is a JSON-encoded Array in this case. ioBroker is storing array that way in objects by using a string and doing json.stringify. So you get it as string and need to do "JSON.parse(val)"

**Comment by kugelkopf123** [comment]
Hi!! 
Yes, converting it back to javascript works fine. Would you like to continue using it in C ++ unfortunately not. It is not possible to parse it as an array. Only as a string.
I want to use JSON to import the data from ioBroker to an ESP8266 and put it on a display.

**Comment by Apollon77** [comment]
I see, can you please show the object definition of that object your are working with?

**Comment by GermanBluefox** [comment]
https://stackoverflow.com/questions/9210528/split-string-with-delimiters-in-c
and then atof(s) for every element.

**Comment by kugelkopf123** [comment]
> I see, can you please show the object definition of that object your are working with?


```
var Pfad= "Wetterstation",
idHistoryTemp1Date = "javascript." + instance + "." + Pfad + ".HistTemp1Date";
idHistoryTemp1 = "javascript." + instance + "." + Pfad + ".HistTemp1";

	createState(idHistoryTemp1, {
		name: "HistTemp1",
		desc: "jsonabfrage",
		type: "string"
	});   
    createState(idHistoryTemp1Date, "", {
		name: "HistTemp1Date",
		desc: "jsonabfrage",
		type: "string"
	});



var MW= 0;
var sum = 0;
var cnt = 0;
var Pfad= "Wetterstation";
var ArrVal=[];
var ArrDate=[];
var arrtest=[];
var idHistoryTemp1 = "javascript." + instance + "." + Pfad + ".HistTemp1";
var end = new Date().getTime();
console.log(end.toLocaleString());
sendTo('sql.0', 'getHistory', {
    id: 'deconz.0.Sensor_13.temperature',
    options: {
        start:      end - 259200000,
        end:        end,
        aggregate: 'none'//, // or 'none' to get raw values,
       // count:      60
    }
}, function (result) {
   
    console.log(result.result[0].val);
    
    for (var i = 0; i < result.result.length; i++) {
       
         arrtest.push(result.result[i].val);
        var tmp = new Date(result.result[i].ts);
        
        if((result.result.length) != i+1){
          
        var tmpP1 = new Date(result.result[i+1].ts);
        }
        var tmp2;
        if (tmp2 == undefined){tmp2 = tmp.getHours();}
       
    
    if(tmpP1.getHours() == tmp.getHours()) {
        cnt ++;
        sum += result.result[i].val;
    }
    else {
        cnt ++;
        sum += result.result[i].val;
        MW = (sum/cnt);
        MW = Math.round(MW*100)/100

        ArrVal.push(MW);


        tmp.setMinutes(0);
        tmp.setSeconds(0);
        tmp.setHours(tmp.getHours()+1);

        ArrDate.push(tmp.toLocaleString("de-DE"));

        cnt = 0;
        MW = 0;
        sum = 0;
    }
    
    }
    
var jsonArrVal = JSON.stringify(ArrVal);
setState(idHistoryTemp1Date,   JSON.stringify(ArrDate));
setState(idHistoryTemp1, jsonArrVal );

console.log("ArrayTemp: " +jsonArrVal);
console.log("ArrDate: "+ArrDate);

});
```

**Comment by Apollon77** [comment]
Ääähm ... but type of the state is string ... so you also get back a string. Everything is ok API and datatype wise. 

You can not create a datapoint with type string and await that the content is returned differently then a string. The adapter can not detect what you really have inside the string.

**Comment by kugelkopf123** [comment]
> You can not create a datapoint with type string and await that the content is returned differently then a string. The adapter can not detect what you really have inside the string.

Yes, thats right. But there is no type "Array" for the state as far as i know. And if you try to write an Array to a State type numbers you get errors. Thats why the question: Is there a quick fix for this...

**Comment by Apollon77** [comment]
let's say it that way. Yes there is a state type "array" (https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#state) ... but to be honest ... try it ... I think it is still sored internally as a string, but may be de-serialized at the boundaries ... if not we need to check this

**Comment by GermanBluefox** [comment]
>still sored internally as a string

that it is.

**Comment by kugelkopf123** [comment]
I think i had tried that a week ago. It throws warnings in the Log. Wrong Type something...

**Comment by GermanBluefox** [comment]
It is not the bug...

**Comment by bratello** [comment]
@GermanBluefox @Apollon77 
Hi guys. I have the same issue, and it seems like we have some inconsistency. First time I pass the js array through the adapter.setState:
```javascript
adapter.setState("myState", {
    val: [{
        name: "Vasya",
        job: "Manager"
    }]
});
```
It's shown correct when I try to fetch it by simpleApi states command:
```javascript
{
  "myadapter.0.myState": {
    "val": [{
        "name": "Vasya",
        "job": "Manager"
    }],
    "ack": true,
    "ts": 1568051725628,
    "q": 0,
    "from": "system.adapter.myadapter.0",
    "user": "system.user.admin",
    "lc": 1568023251392
  },
  "undefined": null
}
```
Once I assign the new array through the set command the array becomes string:
`url/set/?value=[{"name": "Sasha", "job": "Sales"}]`

```javascript
{
  "myadapter.0.myState": {
    "val": "[{
        "name": "Sasha",
        "job": "Sales"
    }]",
    "ack": true,
    "ts": 1568051725628,
    "q": 0,
    "from": "system.adapter.myadapter.0",
    "user": "system.user.admin",
    "lc": 1568023251392
  },
  "undefined": null
}
```

It seems like you handle only the boolean and float value types, setValueFromBody works the same:
[simpleapi.js](https://github.com/ioBroker/ioBroker.simple-api/blob/master/lib/simpleapi.js#L795)

You can put the optional url query argument for type hinting (according to the supported by iobroker value types):
`url/set/?value=[{"name": "Sasha", "job": "Sales"}]&type=array`
Without type argument it will work as before.

Or you can implement separate api entryPoint for the array & object types, if you wondering for backward compatibility, e.g setObjectValue - actually it's up to you. Or please suggest me an API with correct behaviour, socket.io?
Thanks a lot

**Comment by bratello** [comment]
@GermanBluefox @Apollon77 Maybe I need to open new issue?

**Comment by Apollon77** [comment]
No, it is behaving correctly. normally "arrays" are not really supported datatypes for states. only number, boolean and strings are. SO if you need to store an array ALWAYS use "JSON.stringify" and JSON.parse to convert it back.

That it seems t work in some scripts is kind of unexpected and I'm not sure if this will not break at anytimepoint!

**Comment by Apollon77** [comment]
Or to be more clear: also when state.type allows "array" and "object" they should be stored JSON-encoded

**Comment by bratello** [comment]
@Apollon77 Ingo, thanks for the fast reply.
When I need to JSON-encode the array or object, for adapter.setState/getForeignState, or for simpleApi set command? And why we have such inconsistency between adapter.setState and simpleapi.set command? Why simpleapi.states return first time the array value, and the second time the string value? It seems like incorrect behaviour, and the lines of code confirm my assumption there.

**Comment by bratello** [comment]
@Apollon77 @GermanBluefox 
Just let me to clarify why I need this array of objects. I have the esp device with cron, and the set of the cron jobs associated with the cron. Every job configured by **array** of slot objects, every slot configures the time period when the cron job should be active, so this way we can run job every 5 minutes in the morning, and every 10 minutes evening, or whatever you need. This cron job can enable some relay or other external devices, basically it will be used for managing processes in agriculturing systems (watering, ventilation, insolation etc). So the esp device is pretty smaart, it can handle all things independently from mqtt broker - basically because the communication in the field is very unstable and the network damage for one day will cost a lot. But still we need to provide the device configuration from the mqtt broker, just reconfigure it from the office once a month. That's why I need this array type for the state.

**Comment by bratello** [comment]
@Apollon77 Do you want me to offer a patch myself? I think the type hint approach is pretty safe and backward compatible

**Comment by GermanBluefox** [comment]
@bratello Please check github version: https://github.com/ioBroker/ioBroker.simple-api/commit/3fc88e4273c09d7ea9911582f1f02c07f9a2eb8a

**Comment by bratello** [comment]
@GermanBluefox Seems the code should be 
`values.val = JSON.parse(values.value);`
[simpleapi.js#L868](https://github.com/ioBroker/ioBroker.simple-api/blob/3fc88e4273c09d7ea9911582f1f02c07f9a2eb8a/lib/simpleapi.js#L868)
Anyway, as I told before: adapter.setForeignState method, in opposite to the adapter.setState method, can't handle array/json properly. See my previous post. I have tested type=array/object/json with both ack=true/false - same result.

I have reproduced this trouble in my own adapter as following (just few lines in main.js):
```javascript
    let val = [{name:"Vasya"}];
    let ack = true;
    let id = 'gofarmtech.0.devices.IoT8ac1317d9b02.TimerValue.conditionTask';
    

    adapter.setState(id, {
        val: val,
        ack: ack
    });

    val.name = "Sasha";
    adapter.setForeignState(id, val, ack, function(err) {
        if(err) {
            adapter.log.error("setForeignState error" + err);
        }
    });
```
So as you can see, the problem related with setForeignState method implementation. Can you show me where setForeignState implementation located?

**Comment by bratello** [comment]
@GermanBluefox As I can see, the adapter.setForeignState method works through iosocket API by StatesInMemClient class. 
```javascript
    this.setState = function (id, state, callback) {
        if (!client) return;
        client.emit('setState', id, state, callback);
    };
```
So the trouble can be in client emission or on the backend site. The backend located in in iobroker.socketio socket.js, but 'setState' event handler again point it to the adapter.setState. Do you know where the setState landed finally?

**Comment by Apollon77** [comment]
It lands in StatesInMemServer :-)

In fact the whole Socket.io stuff will be deprecated with js.-controller 2.0 because it is completely rewritten there and uses different protocol. So every solution maybe found here needs to be re-verified with js.controller 2.0

**Comment by bratello** [comment]
@Apollon77 @GermanBluefox 
So the problem located here:
[setState method](https://github.com/ioBroker/ioBroker.js-controller/blob/1.5.x/lib/states/statesInMemServer.js#L609)

```javascript
        if (typeof state !== 'object' || state === null || state === undefined) {
            state = {
                val: state
            };
        }
```
When the state comes as simple value (int/string/boolean) - some state boxing going here. But when it comes as object - we assumes that state.val already boxed. This is the reason why state.user & state.from are undefined, btw

And my assumption was correct, because anyway I was able to push array through the simpleApi set command, just make boxing it for the array & object before you going to post state through the adapter.setForeignState:
```javascript
//instead values.val = JSON.parse(values.value);
values.val = {val: JSON.parse(values.value)};
```
at line [simpleapi.js#L868](https://github.com/ioBroker/ioBroker.simple-api/blob/3fc88e4273c09d7ea9911582f1f02c07f9a2eb8a/lib/simpleapi.js#L868)
Just to be clear - it's not workaround, it's for verification only. So the StatesInMemServer should be fixed for this case properly.

I understand that you going to rewrite js-controller 2.0, but I think this case should be included to the 2.0 as well, because it aligns the adapter.setState & adapter.setForeignState behaviours.

**Comment by bratello** [comment]
@Apollon77 @GermanBluefox 
BTW, you can fix the StatesInMemServer easily:
```javascript
        if (typeof state !== 'object' || state === null || state === undefined) {
            state = {
                val: state
            };
        } else if(state && !state.ts && !state.lc && !state.q) {
                //Be sure the state entry it's user defined object but not the states entry
                state = {
                    val: state
                };
        }
```

**Comment by bratello** [comment]
@GermanBluefox  @Apollon77 
So let's make some decision, guys? The patch [3fc88e4](https://github.com/ioBroker/ioBroker.simple-api/commit/3fc88e4273c09d7ea9911582f1f02c07f9a2eb8a) requires the finish up. And the StatesInMemServer requires small fixing. Let's do it till the end of the week?

Thanks a lot in advance!
