### ISSUE TITLE
[Bug] prettyPrint funktioniert nicht wie in der Doku angegeben

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.simple-api#150]
Wenn man bspw. die toggle Funktion nutzt, so bekommt man bei der Nutzung wie in der Doku einen error ausgegeben.

Hier ein Link zur Stelle in der Doku: [Toggle](https://github.com/ioBroker/ioBroker.simple-api/blob/master/README.md#:~:text=%22toggle%22%3A%20%22http%3A//ipaddress%3A8087/toggle/stateID%26prettyPrint%22%2C)

Dort soll man die stateId und prettyPrint mit einem "&" trennen.
Bspw. 
` "toggle": "http://ipaddress:8087/toggle/stateID&prettyPrint"`
Dieses "&" wird aber anscheinend zur stateId hinzu gezählt.
Wählt man wie bei set bspw. als Trennung ein "?", so funktioniert auch beim toggle das prettyPrint.
` "toggle": "http://ipaddress:8087/toggle/stateID?prettyPrint",`

**Comment by Apollon77** [comment]
Ja ? ist korekt, Doku ist falsch ... fixe ich
