### ISSUE TITLE
Renove Tocken

### ISSUE THREAD

**Issue by B4unty** [ioBroker/ioBroker.simple-api#154]
Hello I'm trying to renew my Tocken and bokke this error message

/opt/iobroker/node_modules/iobroker.ring > npm test

> iobroker.ring@3.0.4 test
> npm run test:ts && npm run test:package

> iobroker.ring@3.0.4 test:ts
> mocha --config test/mocharc.custom.json src/**/*.test.ts

/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/lib/cli/config.js:80
    throw createUnparsableFileError(
    ^

Error: Unable to read/parse test/mocharc.custom.json: Error: ENOENT: no such file or directory, open 'test/mocharc.custom.json'
    at createUnparsableFileError (/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/lib/errors.js:514:13)
    at exports.loadConfig (/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/lib/cli/config.js:80:11)
    at loadRc (/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/lib/cli/options.js:162:21)
    at loadOptions (/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/lib/cli/options.js:234:20)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/node_modules/mocha/bin/mocha.js:27:14)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'ERR_MOCHA_UNPARSABLE_FILE'
}

sudo npm i ring-client-api

up to date, audited 931 packages in 4s

83 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating gulp to 3.9.1, which is a SemVer major change.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

added 83 packages, removed 153 packages, changed 16 packages, and audited 861 packages in 16s

77 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-29mw-wpgm-hmr9
Prototype Pollution in lodash - https://github.com/advisories/GHSA-4xc9-xhrj-v574
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
fix available via `npm audit fix`
node_modules/globule/node_modules/lodash
  globule  <=1.1.0
  Depends on vulnerable versions of glob
  Depends on vulnerable versions of lodash
  Depends on vulnerable versions of minimatch
  node_modules/globule
    gaze  0.4.0 - 1.0.0
    Depends on vulnerable versions of globule
    node_modules/gaze
      glob-watcher  <=2.0.0
      Depends on vulnerable versions of gaze
      node_modules/glob-watcher

lodash.template  <4.5.0
Severity: critical
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
fix available via `npm audit fix --force`
Will install gulp@4.0.2, which is a breaking change
node_modules/lodash.template
  gulp-util  >=1.1.0
  Depends on vulnerable versions of lodash.template
  node_modules/gulp-util
    gulp  2.6.1 - 3.9.1
    Depends on vulnerable versions of gulp-util
    Depends on vulnerable versions of vinyl-fs
    node_modules/gulp

minimatch  <3.0.2
Severity: high
Regular Expression Denial of Service in minimatch - https://github.com/advisories/GHSA-hxm2-r34f-qmc5
fix available via `npm audit fix --force`
Will install gulp@4.0.2, which is a breaking change
node_modules/glob-stream/node_modules/minimatch
node_modules/globule/node_modules/minimatch
  glob  3.0.0 - 5.0.14
  Depends on vulnerable versions of minimatch
  node_modules/glob-stream/node_modules/glob
  node_modules/globule/node_modules/glob
    glob-stream  0.2.0 - 5.2.0
    Depends on vulnerable versions of glob
    Depends on vulnerable versions of minimatch
    node_modules/glob-stream
      vinyl-fs  <=1.0.0
      Depends on vulnerable versions of glob-stream
      Depends on vulnerable versions of glob-watcher
      node_modules/vinyl-fs

11 vulnerabilities (2 moderate, 5 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:

**Comment by Apollon77** [comment]
Please open the issue in the repo of the affected adapter ... seems to be riung adapter right? This is simple-api adapter
