### ISSUE TITLE
create states if not exist

### ISSUE THREAD

**Issue by Chris-656** [ioBroker/ioBroker.simple-api#164]
It would be good if with an option --force the state would be created if under useradata_0.
So more flexible data transfers would be possible. 

`http://ipaddress:8087/set/javascript.0.test?value=test?type=string`
or 
`http://ipaddress:8087/set/0_userdata.test?value=1?type=number`

with best regards
Chris

**Comment by Apollon77** [comment]
I'm not sure if we shpuld do this, because this would potentially also create states by just doing errornous requests or such ...
