### ISSUE TITLE
Warning Lets Encrypt with JS Controller 5.x

### ISSUE THREAD

**Issue by Madaraxa** [ioBroker/ioBroker.simple-api#168]
Since i updated to JS Controller 5.x (5.0.2 and now 5.0.3) with Simple-Api Adapter 2.7.2 (this one i have for some time) i get the following warning at adapter Start:

`<html><body>

simple-api.0 | 2023-06-14 07:42:15.343 | warn | Information  for Developer: Using the direct "Let's encrypt" module import is  deprecated and will be removed in the next js-controller version, use  @iobroker/webserver instead
-- | -- | -- | --

</body>
</html>`

**Comment by foxriver76** [comment]
fixed with 2.8.0
