### ISSUE TITLE
Support for SSL cert (letsencrypt) via acme adapter

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.simple-api#172]
At the moment it is necessary to maintain the cert files e.g. as absolute file path in admin basic settings:

![image](https://github.com/ioBroker/ioBroker.simple-api/assets/39678667/d7243eb2-667c-4500-ac45-20708b6eaa5a)

Then it is possible to choose these in instance settings:
![image](https://github.com/ioBroker/ioBroker.simple-api/assets/39678667/eea31ac6-cbe6-4f7d-b821-d81daf2a1cfe)

But this cert files are only renewed by web adapter until v5. Since web v6 acme is the only way.

**Comment by Diginix** [comment]
Any news on this?
I still have to stay on web v5 and can't update to v6.

**Comment by foxriver76** [comment]
fixed with 2.8.0
