### ISSUE TITLE
simple-api with web adapter doesn't work

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.simple-api#18]
I have installed the simple-api adapter (2.0.2) and configured it to be used with the web adapter (2.4.1). I get an error message:
web.0 Cannot start extension "simple-api.0": ReferenceError: commandsPermissions is not defined

**Comment by cburghardt** [comment]
I have installed the simple-api adapter (2.0.2) and configured it to be used with the web adapter (2.4.1). I get an error message:
web.0 Cannot start extension "simple-api.0": ReferenceError: commandsPermissions is not defined

**Comment by Apollon77** [comment]
Please try 2.0.3 from Github, which nodejs version do you use?

**Comment by cburghardt** [comment]
Awesome, that works! Thank you :)
