### ISSUE TITLE
server disk full - after update to 2.0.4

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.simple-api#19]
Hi I have updatedd the simple api and now I have the problem, that daemon.log and syslog files are writing to much - the file sizes are over 5 GB - after downgrade to 2.0.2 the files are ok

I have 3-4 devices which are asking the simple-api adapter - and all this stuff is writen in the log files

did I something wrong

the picture shows the logfile - every couple of seconds there is an new entry - after 3 days the file is 5GB

![Image 14](https://user-images.githubusercontent.com/18462890/60119549-0f9b7d80-977f-11e9-87a3-83e72982953d.png)

**Comment by Apollon77** [comment]
I have no idea where this could come from. Any other updates or really just simple api??  Also such a logging is unknown to me.

**Comment by liv-in-sky** [comment]
I double checked it - did the upgrade to 2.0.4. again.
I have two devices  - which create this error - 
1- wemos d1 which is connected to a matrix display (command: http.begin(url1+ "Setting");
2- win 10 pc which is using "curl http://192.168.178.59:8087/getPlainValue/controll-own.0.fx6300energysaving" to get the datapoint inbot a batch script
3- I do not get any errors if I write to iobroker - only when I try to get data

this message I got with debug on (in iobroker)- strange - because only when I start the instance - then I get this message - only one time

`

simple-api.0 | 2019-06-26 09:47:47.086 | info | http server listening on port 8087
-- | -- | -- | --
simple-api.0 | 2019-06-26 09:47:47.084 | info | Allow states only when user is owner: false
simple-api.0 | 2019-06-26 09:47:47.083 | info | simpleAPI server listening on port 8087
simple-api.0 | 2019-06-26 09:47:47.056 | info | starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.simple-api, node: v10.16.0
simple-api.0 | 2019-06-26 09:47:47.031 | debug | statesDB connected
simple-api.0 | 2019-06-26 09:47:47.011 | debug | objectDB connected
host.raspberry3 | 2019-06-26 09:47:46.711 | info | instance system.adapter.simple-api.0 started with pid 11986
host.raspberry3 | 2019-06-26 09:47:46.696 | info | object change system.adapter.simple-api.0
host.raspberry3 | 2019-06-26 09:47:43.514 | info | instance system.adapter.simple-api.0 terminated with code 156 ()
Caught | 2019-06-26 09:47:43.514 | error | by controller[4]: OBJECT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!{"val":false,"ack":false,"ts":1561464332888,"q":0,"from":"system.adapter.simple-api.0","user":"system.user.admin","lc":1561464332888}
Caught | 2019-06-26 09:47:43.514 | error | by controller[3]: OBJECT1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!null controll-own.0.fx6300energysaving
Caught | 2019-06-26 09:47:43.514 | error | by controller[2]: OBJECT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!{"val":false,"ack":false,"ts":1561464332888,"q":0,"from":"system.adapter.simple-api.0","user":"system.user.admin","lc":1561464332888}
Caught | 2019-06-26 09:47:43.514 | error | by controller[1]: OBJECT1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!null controll-own.0.fx6300energysaving


`
I do not have any other messages (log) and everthing is working - so the data is got by the devices


this is the adapter setting
![Image 2](https://user-images.githubusercontent.com/18462890/60161653-3fd33280-97f8-11e9-86e8-9d131beecd71.png)

maybe privileges/rights  problem ?

DO YOU NEED ANY OTHER INFORMATION

**Comment by Apollon77** [comment]
Which js-Controller Version?

**Comment by liv-in-sky** [comment]
1.5.12

**Comment by Apollon77** [comment]
fixed by 2.0.5 (GitHub and npm/latest soon)

**Comment by liv-in-sky** [comment]
thanx a lot for your help - it's (2.0.5) running without error messages
