### ISSUE TITLE
Add ReSTful-API

### ISSUE THREAD

**Issue by jhedtmann** [ioBroker/ioBroker.simple-api#191]
Somewhere in the documentation it is claimed that simple-api follows a ReSTful-pattern. This is not so. In fact, the pattern provided has no resemblance to a ReST- or ReSTful API other than using the same transport mechanism (HTTP). May I therefore suggest that in a future release an API is provided that follows the above mentioned patterns more strictly.

**Comment by Apollon77** [comment]
use iobroker.rest-api Adapter for a RESTFUL API

**Comment by jhedtmann** [comment]
Thanks for pointing that out, but then please remove the "ReSTful" from the description of this project.

Thanks for all the effort!

**Comment by Apollon77** [comment]
Already done
