### ISSUE TITLE
Let's encrypt" module import is deprecated

### ISSUE THREAD

**Issue by sansonifabio** [ioBroker/ioBroker.simple-api#194]
@Apollon77 

**Describe the bug**  

This warning came up today when I restarted ioBroker.
Greetings
Fabio

Beim Neustart von ioBroker kam heute diese Warnung.
Grüße
Fabio

**PS: Ist wohl hier das selbe: https://github.com/ioBroker/ioBroker.simple-api/issues/168 dann bitte löschen oder schließen.**

**Screenshots & Logfiles**  

**simple-api.0 | 2024-04-14 10:30:01.619 | warn | Information for Developer: Using the direct "Let's encrypt" module import is deprecated and will be removed in the next js-controller version, use @iobroker/webserver instead**

****Versions:****  
 - Adapter version: 2.7.2
 - JS-Controller version: 5.0.19
 - Node version: 18.20.2
 - Operating system: Debian Bookworm
 - NPM: 10.5.0

**Comment by Baenker** [comment]
kommt bei mir auch

**Comment by foxriver76** [comment]
fixed with 2.8.0
