### ISSUE TITLE
neuer Methode 'setFromBody'

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.simple-api#2]
Ich nutze die Simple-API u. a. für callbacks aus anderen IoT-Projekten. 
Einige Projekte haben die Callbacks als GET, andere als POST realisiert, was zunächst bei einer reinen URL per set bzw. setBulk nutzbar wäre. 
In meinem aktuellen Fall ist es nun so, dass das Gerät (Nuki-Bridge) einen POST an die für den callback hinterlegte URL mit den Nutzdaten im JSON-Format im Body sendet.
Simple-API müsste nun also den Datenpunkt aus der URL entnehmen und den Inhalt des Body in den Datenpunkt schreiben.

**Comment by Apollon77** [comment]
how the json would look like?
You can in general implement it and send in as pull request and we will check it

**Comment by truegreyhound** [comment]
Hello Ingo,

 

the JSON-data in the body looks like 

{"nukiId": 91049449, "state": 3, "stateName": "unlocked", "batteryCritical": false}

 

I’m not so firm with Java/JavaScript, so I think this is not an real solution for me.

 

Regards

GH

**Comment by Apollon77** [comment]
Looks like a very specific body for your usage ... so we would need some kind of "config" where the state-ID and where the value is in to be able to parse the body data ... hm ...

**Comment by truegreyhound** [comment]
The content from the body should complete in an datapoint as String or Object. The state-ID is in the url

 

<state-ID> = <bod>

**Comment by Apollon77** [comment]
Idea put into Trello https://trello.com/c/CHzoDHwc

**Comment by truegreyhound** [comment]
Hi,
weil für mich doch wichtig und der Code überschaubar habe ich gerade einen Pull-request dazu eingereicht. -->  #[setValueFromBody](https://github.com/ioBroker/ioBroker.simple-api/pull/3)

**Comment by Apollon77** [comment]
fixed by https://github.com/ioBroker/ioBroker.simple-api/commit/2154fbdb96a4248186e22dda729d19754795ea20
