### ISSUE TITLE
get/set-functions doesn't work with stateIDs which include #

### ISSUE THREAD

**Issue by kisun69** [ioBroker/ioBroker.simple-api#201]
I have many object-folders which include # in their name ( like for example: shellyplusplugs#fcb4672661c0#1 ).

if I run: 

curl http://192.168.0.69:8087/get/javascript.0.ShellyVerbrauch.shellyplusplugs#fcb4672661c0#1.name

it gave me this error:

{"error":"datapoint \"javascript.0.ShellyVerbrauch.shellyplusplugs\" not found"}

So, everything after the # will be ignored from the api.

I also tried it on an other example. I  created 2 object-folders in 0_userdata,0. Both with a "state" called text:
0_userdata.0.Test-Object-001.text
0_userdata.0.Test-Object#002.text

So,
>>> curl http://192.168.0.69:8087/getPlainValue/0_userdata.0.Test-Object-001.text/?prettyPrint
returns: "hello"   (which is the saved value)

and:
>>> curl http://192.168.0.69:8087/getPlainValue/0_userdata.0.Test-Object#002.text/?prettyPrint
returns: error: datapoint &quot;0_userdata.0.Test-Object&quot; not found 

simple-api version: 2.8.0
js-controller version: 5.0.19 
os: raspian

**Comment by Apollon77** [comment]
Might it be needed to encode this character? Usually for webpages these are anchors and so ignored by "browsers" ... no idea what curl does ... maybe there is s a setting to prevent him from cutting that out?

**Comment by kisun69** [comment]
Oh, great. that helps a lot.

if I use %23 instead of # it works like expected. 

Thanks. For me this issue can be closed.

**Comment by kisun69** [comment]
Oh, great. that helps a lot.

if I use %23 instead of # it works like expected. 

Thanks. For me this issue can be closed.
