### ISSUE TITLE
getBulk only return VAL/TS

### ISSUE THREAD

**Issue by rocklobster42195** [ioBroker/ioBroker.simple-api#21]
Hi,
getBulk only returns VAL and TS. The ID is missing.

`http://192.168.7.87:8087/getBulk/hm-rega.0.14040,javascript.0.REG77.Klima.schwuelewarnung,[...]`

`[{"val":10.7,"ts":1562482862985},{"val":0,"ts":1562482856282},[...]`

I shortened request and response for simplicity, Did I miss something?
Thanks,
Boris

**Comment by Apollon77** [comment]
The order of the response is "as in the request". But yes could be added

**Comment by rocklobster42195** [comment]
I was a little confused, because the API-guide says 

> get many states with one request, returned as object with ID as key and val/ts as subobject

**Comment by Apollon77** [comment]
Than doc is wrong :-(

**Comment by Apollon77** [comment]
I added the id to the response objects and updated documentation. Please try GitHub version

**Comment by rocklobster42195** [comment]
Nice! It´s working. Thank you.
