### ISSUE TITLE
save settings not possible

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.simple-api#23]

**Comment by Apollon77** [comment]
Do youngsters some more details?

**Comment by Diginix** [comment]
The config dialog of the instance can't be saved, no matter what small changes are done. E.g. authentication can't activated or port isn't changeable.
Nothing happens on click on the save button.

![simple_api_config](https://user-images.githubusercontent.com/39678667/66736116-a42e0680-ee68-11e9-881b-2ebcff0c30e7.png)

**Comment by Apollon77** [comment]
I can not reproduce it. tested on two systems with newest js.controller. Which Admin version is used?

**Comment by Apollon77** [comment]
ALternative: Does browser console show any errors?

**Comment by Apollon77** [comment]
Ok, I can reproduce it now

**Comment by Apollon77** [comment]
ReferenceError: getWhiteListSettings is not defined
index_m.html:168:9

**Comment by Diginix** [comment]
nodejs 10.16.3
npm 6.9.0
js-controller 1.5.14

**Comment by Apollon77** [comment]
fixed by 2.3.2 (on Github, latest repo later)
