### ISSUE TITLE
API with certain user (other then admin) doesn't work.

### ISSUE THREAD

**Issue by Gammenon** [ioBroker/ioBroker.simple-api#27]
Hi everyone,

probably it's not a bug and I just get something wrong. I'm new to the iobroker world.

I installed the adapter and created an intance and set up everything to use authentication.
![grafik](https://user-images.githubusercontent.com/34088644/71071671-50e47700-217d-11ea-88e6-5b20ce6fe94e.png)

On the other side I created a group and a user, set the privileges to "read" on every point where it is possible, then put the new user in it.

No matter what I try, and even if I put the new User into the Administrator group I always get the API return
`{"error":"permissionError"}`

If on the other hand I use the Admin user, everything works fine.

Is this some sort of misbehaviour or am I doing something wrong?

**Comment by Apollon77** [comment]
Please show the exact settings for the user and group

**Comment by Gammenon** [comment]
User:
![grafik](https://user-images.githubusercontent.com/34088644/71094643-9a4bbb00-21ab-11ea-9752-fe2f4ee07119.png)
Group:
![grafik](https://user-images.githubusercontent.com/34088644/71094675-a6d01380-21ab-11ea-84f4-7e3c6748ef6c.png)

But as I said, same behaviour when I put the user into the Administrator group.
From my perspective there isn't much more to configure, right?

by the way:
simple api version 2.3.2
Node.js: v10.17.0
NPM: 6.11.3
ioBroker.admin 3.6.12

**Comment by Apollon77** [comment]
You always need object list rights. Please try it with adding this. 

Also: adding another user to administrators group might not work - we need to fix this. Alternative is s new group with all rights enabled as administrator also shown.

**Comment by Gammenon** [comment]
oh yeah, that was the issue. I'm ashamed of myself. I don't know how I could miss this one.
I beg your pardon and thanks for your help ! ;)
