### ISSUE TITLE
Problem mit "#“ Zeichen in Device-ID (z.B. Shelly-Devices)

### ISSUE THREAD

**Issue by StopAndG0** [ioBroker/ioBroker.simple-api#28]
Ich würde meine Shellys gerne über Simple-Api steuern. Leider geht das nicht, da das "#"-Zeichen in den ID´s der Shellys nicht interpretiert wird. Ersetze ich "#" durch "%23" funktionieren einige Funktionen, aber leider nicht alle.

Das Problem wurde auch [hier](https://forum.iobroker.net/topic/16885/simple-api-stateid-mit) bereits besprochen und ist in der v.2.0.2 wohl beseitigt worden.

Ich nutze die aktuellen Stable-Version (v2.3.2). Hat sich hier der Fehler evtl. wieder eingeschlichen?

**Comment by chris25197** [comment]
Hab gerade geschaut, bei mir funktioniert es. Mit der von dir angegebenen Version.

Am 28. Dezember 2019 12:49:37 MEZ schrieb StopAndG0 <notifications@github.com>:

**Comment by StopAndG0** [comment]
Also bei mir geht es definitiv nicht.

Hier die Ausgaben im Browser:
<img width="775" alt="grafik" src="https://user-images.githubusercontent.com/48774481/71555968-781b2e00-2a32-11ea-9f73-447df287e788.png">

<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/48774481/71555975-94b76600-2a32-11ea-941e-b2e7480648c2.png">

**Comment by Apollon77** [comment]
Ääähm ... naja im Browser geht das so nicht da der Browser ein # als Seiten Anker nutzt. Da kann der Adapter nix für. 

Versuch mal mit curl !

**Comment by StopAndG0** [comment]
Aha Ok, mein Fehler. Ich wusste nicht, dass # im Browser so nicht funktioniert. Mit curl geht es! 
Ich nutze ein Script zum Import der Shelly-ID´s in die HA-Bridge, dann muss ich "#" eben durch "%23" ersetzen.

Danke für die Aufklärung.
