### ISSUE TITLE
Http Request from local IP camera is not processed

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.simple-api#30]
Dear experts,

I have setup the simpla api adapter in order to receive set-commands from my IP cameras (funtionality: alarm server). So if the camera recognizes movements the camera sends out an http request to the iobroker port 8087 (IObroker is installed on a Pi4).
There instar cameras and the manufacture assumes that there are timeouts or anything else by setting up the http request between the camera operating system and the iobroker. I have big doubts because one or two out of ten camera are getting through via there set-hettp reuqest..

Are there a chance to log the connection attempts via this port? Do I need to use a script for this? Or is the incidents log of iobroker showing all attempts to access the API = change states?
How do professional users track the external access to this simple API adapter?

**Comment by Apollon77** [comment]
You can try to set the adapter to debug loglevel, then you might see the incoming requests

**Comment by Diginix** [comment]
I have also an Instar cam and uses simple-api for exactly the same purpose.
Is your simple-api url working in a browser without existing iobroker session (incognito tab)?
The Instar web UI shows you the created url out of your made settings (red highlighted).
If the url is working as request from a browser it is ok and you have to check the settings in Instar UI.

![image](https://user-images.githubusercontent.com/39678667/75616601-40745380-5b53-11ea-9e97-8bec0dc98bb9.png)
