### ISSUE TITLE
Adapter lässt sich nicht installieren

### ISSUE THREAD

**Issue by frankyboy1973** [ioBroker/ioBroker.simple-api#32]
Folgende Fehlermeldung
![Api](https://user-images.githubusercontent.com/46169800/73669556-f0b38100-46a7-11ea-91d3-c3123cb9e20d.JPG)

**Comment by Apollon77** [comment]
It seems your iobroker installation is damaged. try to reinstall js-controller

**Comment by frankyboy1973** [comment]
Hi, one week ago i had installed everthing new, new image, new iobroker. I can install all the other adapters i need, alexa, fritz, tr-064, node-red, sonoff, js-scrip, but when i try to install the Api Adapter i become this error and i can not reach the iobroker admin site (IP:8081)

**Comment by Apollon77** [comment]
Please contact us in Forum ... I could only repeast what I already wrote. Ad that Admin is now unreachable shows that something went strange and js.controller seems broken

**Comment by frankyboy1973** [comment]
I have tried new installation, new Image, Raspian Buster on Raspian Pi 4 with 4GB, new Iobroker installation, Add Adapter Api, same Error, and the Iobroker is not reachable, opt/iobroker not found, all other Adapters working before. . Iobroker ist completly working with all the other adapters i have installed before, but when i install Api it is broken.
Sorry, but i am not very good in English.

**Comment by Apollon77** [comment]
Deutsch ist auch ok. Am besten bitte wirklichem Forum melden. 

Also wenn du iobroker frisch installierst und dann direkt simple api installierst kommt der Fehler?
