### ISSUE TITLE
prettyPrint not pretty

### ISSUE THREAD

**Issue by danny030** [ioBroker/ioBroker.simple-api#36]
Hi,
just came across this as I migrated from a Raspberry 3 to 4.

Same browser window (Chrome), just different tabs: Pretty print in 2.4.5 (not pretty) vs 2.3.2 (very pretty)

2.4.5
![CACC61A0-206A-45B7-8534-6793F392B9FB](https://user-images.githubusercontent.com/26109035/81728692-25935900-948b-11ea-91f4-b7783986e5b3.png)

2.3.2
![68E241E8-DA74-474E-A91A-3ECBAF5E2DB8](https://user-images.githubusercontent.com/26109035/81728711-2af0a380-948b-11ea-8cc3-99f784f6b018.png)

**Comment by Apollon77** [comment]
can you please check in the "broken" version how the really returned content looks like?
In 2.3.3 it seems that the response type was changed from test/plain to text/html ... so the browser is interpreting it as html now and so all formattings are differently shown.

In fact the browser is a bad way to test API responses ... best use CURL or such

**Comment by danny030** [comment]
Ok, understood. Thought "prettyPrint" does mean show pretty output for the browser to make it easily readable. When using curl, it looks fine. See attached. If you say this is expected, then it's fine.
![E3DC4ADC-24EB-4BCD-9B4A-1F2ED023CB14](https://user-images.githubusercontent.com/26109035/81979173-d1c07580-962c-11ea-8493-c1a96fda79ee.png)
