### ISSUE TITLE
Internal Server Eror 500

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.simple-api#4]
Wenn mit setBulk mehrere Werte gesendet werden ist die Response Internal Server Error 500 die Werte werden jedoch in IOBroker geschrieben.

**Comment by Apollon77** [comment]
Bitte ein Beispiel des POST requests hinzufügen. Die Tests funktionieren und testen an sich auch setBulk mit mehreren Werten und da tut alles.

**Comment by baennjer** [comment]
Das ist die Funktion mit der 5 Temperaturen an IOB gemeldet werden. Im Prinzig funzt die Übertragung und die Werte werden in IOB aktualisiert, lediglich kommt statt 200 die 500 mit Internal Server Error.

void melde_IOB() { 
  WiFiClient client; 
  if (!client.connect(host, 8087)) {
    Serial.println(zeitstempel() + "  Fehler: Verbindung zum IOB konnte nicht aufgebaut werden");
     delay(100);
    return;
  }
meldung = "GET /setBulk?" + IOBNameTemp1 +"=" + Temperatur1 + "&" + IOBNameTemp2 + "=" + Temperatur2 + "&" + IOBNameTemp3 + "=" + Temperatur3  + "&" + IOBNameTemp4 + "=" + Temperatur4   + "&" + IOBNameTemp5 + "=" + Temperatur5 + "&prettyPrint HTTP/1.1";
  client.println(meldung); 
  Serial.println(meldung);
  
  client.println();
  delay(1000); 

  Serial.println();
  int i = 0;
  String zeile = "";
  while(client.available()){ 
    i ++;
    zeile = client.readStringUntil('\n'); 

    if (i == 5) {//Timestamp
      Serial.println(zeile);
      letzteMeldungIOBzeit = zeile;
    }
    if (i == 10 || i == 11) {//quittung, bei setBulk nur erster wert
      Serial.println(zeile);
    }
  }

  Serial.println("Werte an IOB gemeldet, " + letzteMeldungIOBzeit);
  letzteMeldungMillis = jetztMillis; 
  
  IOBTemp1 = Temperatur1;
  IOBTemp2 = Temperatur2;
  IOBTemp3 = Temperatur3;
  IOBTemp4 = Temperatur4;
  IOBTemp5 = Temperatur5;
}

**Comment by Apollon77** [comment]
Jetzt sind natürlich noch die Ausgaben des Skripts interessant Also wie EXAKT sieht der Request und Response aus?
Weiterhin den simpleapi Adapter bitte im Debug-Modus laufen lassen (unter Instanzen oben links den Expertenmodus einschalten und dann in der Spalte Loglevel auf "Debug" setzen). Und das log von so einem Request hätte ich auch gern noch :-) Danke

**Comment by Apollon77** [comment]
PS: Error 500 kann bei setBulk an sich nur vorkommen wenn der Statename nicht existiert/gefunden werden kann oder nicht geschrieben werden kann. Die Debug-Ausgaben sollten hier Infos geben

**Comment by baennjer** [comment]
![image](https://user-images.githubusercontent.com/32200998/30795642-c61305c2-a1ce-11e7-9f96-ba8759420e68.png)

**Comment by Apollon77** [comment]
Gratuliere. Bug gefunden. Versuch mal die Version vom Github bitte

**Comment by baennjer** [comment]
Danke für deine Mühe. Da das System läuft werde ich erst mal nichts machen. Wie gesagt die Werte werden ja eingetragen... Ich hatte den Thread nur eröffnet weil irgendwie am Anfang der Arduino Sketch den Zeitstempel nicht aus der Response gelesen hatte. Deswegen dachte ich dass das am 500 liegt.
