### ISSUE TITLE
decoding for state Ids with : in it

### ISSUE THREAD

**Issue by michidede** [ioBroker/ioBroker.simple-api#54]
**Describe the bug**  
it seems ":" cant be decoded

**To Reproduce**  
1. http://"ip-adr...":8087/getPlainValue/smartmeter.0.1-0%3A1_8_0__255.value
2. no Values found

**Expected behavior**  
test in Browser
http://"ip-adr...":8087/getPlainValue/smartmeter.0.1-0:1_8_0__255.value
works fine

**Screenshots & Logfiles**  
HTC received: error: datapoint &quot;smartmeter.0.1-0%3A1_8_0__255.value&quot; not found

**Versions:**  
 - Adapter version: 2.5.2
 - JS-Controller version: 3.1.6
 - Node version: 10.23.2
 - Operating system: loxone/Win

**Additional context**

**Comment by Apollon77** [comment]
Please try next version
