### ISSUE TITLE
Feature Request: support of mp4/jpg in Simple API

### ISSUE THREAD

**Issue by thomasklein1975** [ioBroker/ioBroker.simple-api#91]
Hi,

it would be great if links like these:

http://raspberrypi-iob:8082/ring.0/stickup_52891477/livestream52891477_1634375007396.mp4
http://raspberrypi-iob:8082/ring.0/stickup_52891477/snapshot52891477_1634375007284.jpg

would be supportet in/by SimpleAPI

**Comment by Apollon77** [comment]
Are you sure it is about simple-api? What exactly you mean?
Do you want to get files ourt of the iobroker storage? This si already possible using web adapter ...

**Comment by Apollon77** [comment]
ok, tell me where the ring0 files are located in /opt/iobroker/iobroker-data/files/.

**Comment by thomasklein1975** [comment]
> And in fact that the files are in ring.admin also makes no sense but this is an adapter dev topic.
this was done by me.

Sorry for confusion. I will ask at IOT Adapter
