### ISSUE TITLE
Add "parseJson" option for strings (to return json instead of strings)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.simple-api#96]
## Situation

At the moment, I store JavaScript Objects directly into the Database. But: This leads to a warning since js-controller 3.3:

```
State value to set for "lametric.0.mydatadiy.obj" has to be type "string" but received type "object"
```

So I'm using `JSON.stringify()` to store values as a string to avoid that type issue with my state:

```
{
    "_id": "mydatadiy.obj",
    "type": "state",
    "common": {
        "name": "My Data (DIY) frame data",
        "type": "string",
        "role": "json",
        "read": true,
        "write": false
    },
    "native": {}
}
```

## Problem

I'm using the simple api to get the **plain value** (which will be processed externally). This is my request:

```
http://172.16.0.219:8087/getPlainValue/lametric.0.mydatadiy.obj/
```

### Current situation (save object)

```javascript
this.setState('mydatadiy.obj', {val: {'frames': [{text: 'Adapter stopped', icon: 'a9335'}]}, ack: true});
```

**Leads to error, but works.**

Output with type `object` (this is what I need):

```json
{"frames":[{"text":"Adapter stopped","icon":"a9335"}]}
```

### After bugfix (save string)

```javascript
this.setState('mydatadiy.obj', {val: JSON.stringify({'frames': [{text: 'Adapter stopped', icon: 'a9335'}]}), ack: true});
```

Output with `JSON.stringify()` and type `string` (this is what I get when I fix the issue above):

```
"{\"frames\":[{\"text\":\"Adapter stopped\",\"icon\":\"a9335\"}]}"
```

**This is (technically) correct**. But ... you see the problem. I cannot fix this issue right now, since the target system is expecting correct json payload instead of a string with escape characters. See https://github.com/klein0r/ioBroker.lametric/issues/45

## Solution A

Add a `parseJson` option as GET parameter to return the data correctly.

## Solution B

Automatically parse json if the states role is `json` (see above).

**Comment by GermanBluefox** [comment]
Please see 2.6.2
https://github.com/ioBroker/ioBroker.simple-api#getplainvalue

![image](https://user-images.githubusercontent.com/4582016/141446421-4faf34df-5865-470f-b7b7-bfe48f720113.png)

**Comment by klein0r** [comment]
Awesome! Thank you
